version: '3.7'

services:
  my-api:
    image: compliment-generator-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    volumes:
      - dbdata:/data/db
    ports:
      - "27017:27017"

volumes:
  dbdata: