version: '3.7'

services:
  my-api:
    image: my-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - mynetwork

  mongodb:
    image: mongo
    volumes:
      - dbdata:/data/db
    ports:
      - "27017:27017"
    networks:
      - mynetwork
volumes:
  dbdata:
networks:
  mynetwork: